on: push
jobs:
  build-push:
    name: Build and Push container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: build and push to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/Testing-DH:latest

  deploy:
    name: Deploying the app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster
        run: kubectl get pods -A
      - name: Helm Installing
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0
        id: install
      - name: Checking Helm
        run: helm version
      - name: Deploying with Helm
        run: |
          helm upgrade --install testing-digital-house ./chart/testing-digital-house --values=deploy/scopes/main.yaml --set image.tag=latest --wait --timeout "3m0s"

